restcountryapi:
   access_key: f16479a027a8f0d6c8c1082aa65444c7
   
spring:
  data:
    mongodb:
      uri: mongodb+srv://dbuser:dbuser@ng-web-cluster.xbgxd.mongodb.net/playerdb?retryWrites=true&w=majority

server:  servlet:    context-path: /rcsapp
    
logging:  file:    name: log/application.log
    

management:
 endpoints:
   web:
    exposure:
      include: info,health
 endpoint:
   health:
     show-details: always
 health:
   db: 
    enabled: true
   defaults:
     enabled: true